spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc201910?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
  devtools:
    restart:
      enabled: true
mybatis:
  type-aliases-package: com.colin.bean
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8090